### ISSUE TITLE
Error: Cannot read property 'locationId' of undefined

### ISSUE THREAD

**Issue by proimpel** [dehsgr/node-red-contrib-evohome#1]
Hello,
in my house I have an EvoHome system and I was trying to use the package you created.
After entering EvoHome login credentials I immediately received the data correctly.
After a while I started getting this
"msg: error
"TypeError: Cannot read property 'locationId' of undefined" "
and there is no way to have it read correctly.

How can I do?
THANK YOU

**Comment by dehsgr** [comment]
Hi,

What interval did you set? I think your interval is too short and Evohome servers are blocking you. Try to set interval min. once per 30 secs and leave some feedback if it will run again after some time.

Thank you

**Comment by proimpel** [comment]
Hello,
I also thought that was the problem, but the time set is equal to 300 ...
![immagine](https://user-images.githubusercontent.com/53794618/62519470-ec5af800-b82b-11e9-883e-806469b0e345.png)

**Comment by dehsgr** [comment]
What if you try to set interval to 60 secs?

**Comment by proimpel** [comment]
Nothing changes.
I also tried removing and re-installing everything

![immagine](https://user-images.githubusercontent.com/53794618/62521426-f1ba4180-b82f-11e9-8f98-e570805efdbb.png)

**Comment by dehsgr** [comment]
You should disable your flow for around 1 hour that there is no communication with Honeywell that you‘ll get removed from block...

**Comment by proimpel** [comment]
Hi, Good News ....
I stopped the requests for about 3 hours, I restarted but the problem came up again.
Then I removed and uninstalled the palette, stopped and restarted node-red and miraculously went.
So far it seems to be working properly

I'll update you on developments.

THANK YOU

**Comment by dehsgr** [comment]
I'm happy that it is working for you now.

Thanks for your feedback.

**Comment by mijnschoen** [comment]
Hi @dehsgr,
I see exactly the same behavior here. Using an interval of 60, all worked well for a moment but suddenly I only get the warning "cannot read property 'locationId' of undefined".
After uninstalling and restarting nodered, all worked well for 30 minutes after which it stopped again. 

Then I found the evohome-session global variable. While I was getting the errors, I then deleted this global variable and that fixed the issue.

So it's looks like something goes wrong with the session. Is there a way to debug what is happening here?

Kind regards,
Martijn

**Comment by sveco86** [comment]
@dehsgr - problem still exists, I suggest to open this issue

**Comment by proimpel** [comment]
Hi,
I do not have problems.
Everything has been working regularly for about six months (v.1.0.4)

![immagine](https://user-images.githubusercontent.com/53794618/70410911-edf23200-1a50-11ea-9d5a-381b75a16a56.png)

**Comment by pmjgeraeds** [comment]
> Hi,
> I do not have problems.
> Everything has been working regularly for about six months (v.1.0.4)
> 
> ![immagine](https://user-images.githubusercontent.com/53794618/70410911-edf23200-1a50-11ea-9d5a-381b75a16a56.png)

Hi ProImpel:
I have the same problem as above... what interval did you use ?
gr. Pascal

**Comment by proimpel** [comment]
Hi pmjgeraeds,
I use 60sec.

![immagine](https://user-images.githubusercontent.com/53794618/70599726-2ed37d80-1bee-11ea-900e-bcfa421ad006.png)

![immagine](https://user-images.githubusercontent.com/53794618/70599800-62160c80-1bee-11ea-8432-eda51ae02909.png)

**Comment by R-dehaan** [comment]
I have the same situation over here, after a couple of hours get the error cannot read property 'locationId' of undefined. Polling frequency set to 60s.

I also haveshut down node-red for a couple of hours as suggested above, but within the day the error comes back. Tried reinstalling but problem keeps existing.

**Comment by pmjgeraeds** [comment]
Hi R-dehaan and Proimpel,
as "mijnschoen" suggested, I have removed evohome-session global variable.
and since then the software is running stable (it is running on a interval of 600 sec... I do not dare to make it faster) for over 24 hrs now.....
maybe this helps... athough I do not understand why at all.
kind regards Pascal

**Comment by proimpel** [comment]
Hi,
did you read my post last August 6th?
(look down)

![immagine](https://user-images.githubusercontent.com/53794618/70649127-cbc50380-1c4c-11ea-950e-df40869280a6.png)

**Comment by pmjgeraeds** [comment]
Hi Proimpel,
yes I did but unfortunatly after 2 or 3 samples the problem reoccured again.
So therfore I tried what mijnschoen suggested.... and then it is somehow running stable.
So wish me luck ;-)

**Comment by R-dehaan** [comment]
Deleted also my evohome-session global variable. Let's see if this solves the problem, fingers crossed

**Comment by sveco86** [comment]
Can you help me how to delete evohome-session global variable? Thanks.

**Comment by R-dehaan** [comment]
allright, 20 hours later and still running... seems promosing

@sveco86 you can delete variables by using hte menu on the right. See picture.
First you it is empty but by refreshing it you will see the variables.
When you click on the variable you can delete it simply by pressing the recylce bin button.

![image](https://user-images.githubusercontent.com/58786798/70737358-9a167000-1d12-11ea-8f55-26b762be67a9.png)

**Comment by pdbayes** [comment]
I am having this issue after running happily for months. I deleted the session variable and worked for a while then stopped again, twice. I am querying every 60 seconds. Is it possible to delete the session variable automatically?

**Comment by dehsgr** [comment]
@pdbayes last fix on #5 should resolve your issue.

**Comment by FreekBos** [comment]
Hi, I have exactly the same here. Regardles of the interval, the connection gets obstructed as per earlier descriptions from other contributors. Is there anything we/I can do? Is there something you can change in the interface? Please help?

On a second note, what is the exeact syntax for the 3 options in the set-command(s)?
I currently have:
- zone id only: thermostat revert back to the schedule - { id: "1234567" }
- zone id and temperature: temperature until next scheduled time - { id: "1234567", temperature: 22 }
- zone id, temperature and time:ll: set a temporary setpoint until the given time, then revert back to the schedule - { id: "1234567", temperature: 22, endtime: "22:00:00" }
NodeRed doesn't accept temperature and endtime without quotes yet if I surround them with quotes, it doesn't work. Therefore I turn to you for the exact syntax. Can you help too?

Thanks,
FB

**Comment by dehsgr** [comment]
@FreekBos the format of time an temperature normally depends on your localized formats. Go put temperature in quotes is not needed.

As I am not able to reproduce connection issue; I cannot provide a fix for that. A can only assume there is to much communication to the service from your site, wich is causing a temporary block. But there is nothing I can do.

**Comment by FreekBos** [comment]
Hi @dehsgr 
Thanks for responding so quick. I'm super happy you've created these nodes and I think anyone with Evo2+something with IOT ought to use is ;-)

From NodeRed i get this output out of the Status-node: e.g.
{"id":"1069222","name":"badkamer","currentTemperature":18,"targetTemperature":17.5}
(sidestep: Can I query 1 "room" or ID or is it array always?)


When I put in "{ "id": "1069222", temperature: 21 }" I get a complaint from NodeRed: "SyntaxError: Unexpected token t in JSON at position 18" (I select the JSON-input) or is it a string to input? When I put in either, it doesn't result in any activity on the Evo2.
When I put in  { "id": "1069222", "temperature": "21" } or { "id":"1069222", "targetTemperature":"21" } same... I'm running out of options ;-(

As to the "TypeError: Cannot read property 'locationId' of undefined"-message: I can confirm as soon as I try to "set" something, the connection drops. I doubt it's the frequency.. On 120 seconds  it didn't improve. After 3 state-requests it consistently goes into error and I have to delete the variable. I remember back in the days (about 4-5 years ago, the Honeywell-app had similar problems (and communication broke down)
I do confirm the "variable"-story: when I delete the variable, the process flows again. For now I manually poll.

Thanks for your patience and kind regards,
F

**Comment by FreekBos** [comment]
Hi, just a small addidtion:
- it seems the "set" temperature actually makes it to Evo2.
However, it does not change the Evo2-display/computer i.e. it does not reflect on the computer the target temperature actually changed. How is that in your(s) situation?
Hope this helps

**Comment by dehsgr** [comment]
Did you wait for first status to be received, until you performed your set request? Only status requests generate a token. And of course you have to send JSON...

**Comment by dehsgr** [comment]
The update from EVO to the computer/display is out of my reach and could take a while.

**Comment by FreekBos** [comment]
> The update from EVO to the computer/display is out of my reach and could take a while.

I found the syntax for my situation: {"id":"1069222","temperature":"15"}....

Apart from the  "TypeError: Cannot read property 'locationId' of undefined"-message it seems to work now... I hope someone/anyone can get to the fixing of the  by e.g. deleting the variable from NodeRed upon receiving the error-messag ;-)

Thanks @dehsgr
