### ISSUE TITLE
Error: Cannot read property 'locationId' of undefined  

### ISSUE THREAD

**Issue by Blaven1** [dehsgr/node-red-contrib-evohome#12]
This still seems to suffer from the above bug in 1.0.6.
I ran on exisitng Pi setup - ok at the start but failed within an hour (not exactly sure on time, but less than an hour) with the above error.

Polling frequency was set to 300.

Hopefully this bug can be fixed.

thanks.

**Comment by dehsgr** [comment]
Hi, I suggest to take a look at issue #1. There are a lot of tips. I‘m not able to reproduce this issue here. 😢
