### ISSUE TITLE
Permanent Override

### ISSUE THREAD

**Issue by hspjanssen** [dehsgr/node-red-contrib-evohome#13]
Hello,

Is it also possible to integrate permanent override?

Thanks

**Comment by dehsgr** [comment]
@hspjanssen I would like you to manually update your node to the current version here within the repository. Afterwards you should be able to set permanent override as documented within [ReadMe](https://github.com/dehsgr/node-red-contrib-evohome/blob/master/README.md). Please give me feedback if this is working. I'm not able to test any changes as I'm not owning any evohome system. If you confirm changes are working, I'll push a new version to NPM.

**Comment by dehsgr** [comment]
@hspjanssen any feedback available? Does permanent override work for you now (see above)?

**Comment by hspjanssen** [comment]
Hello,

Many thanks for the update, I saw it, but due to lack of time not able to test. Will try this weekend, will let you know.

Many thanks and kind regards

**Comment by hspjanssen** [comment]
Hello,

As far as I can see, it works, many thanks!

I just switched over to a nanoCUL/HGI80 so that I can also see the valve settings.

Best wishes.

**Comment by dehsgr** [comment]
Thanks for getting back, @hspjanssen. I just published the package for all. 

Happy new year and best wishes too.
