### ISSUE TITLE
temperature keeps jumping back

### ISSUE THREAD

**Issue by psy0rz** [dehsgr/node-red-contrib-evohome#16]
Every time i change the temperature via node red, it seems to accept it and after 1 minute jumps back to 21 degrees:

![image](https://user-images.githubusercontent.com/1179017/155120225-d2dddfea-8675-4a38-b76a-a91d417ac78f.png)

I origininally tried with the id as string but that had the same result. No matter what temperature i set, it keeps jumping back.

**Comment by dehsgr** [comment]
@psy0rz you should give more details for being able to help you, e.g. What is the payload you use to set the temperature...

**Comment by dehsgr** [comment]
Okay. My mistake. I just saw you were providing the payload. Sorry for that.

**Comment by psy0rz** [comment]
yeah i just recently discovered you can just "paste" images into github comments and it magically uploads it :)

**Comment by dehsgr** [comment]
I would like you to add 

> console.log(response.body);

between line 181 and line 182 in your evohome.js and give me the log message you'll receive in your console. Thanks.

**Comment by dehsgr** [comment]
Further Honeywell tells us the following (which we are relying on):

> System modes, Zone overrides and Inheritance
> TCC locations can support up to six distinct operating modes: Auto, AutoWithEco, Away, DayOff, HeatingOff, and Custom. Not all systems support all modes.
> 
> Zones support three setpoint modes: FollowSchedule, TemporaryOverride, and PermanentOverride but ‘inherit’ an operating mode from their location (the actual algorithm for this is a little more complicated than indicated below - please see the vendor’s documentation).
> 
> For FollowSchedule, a zone’s setpoint (target temperature) is a function of its scheduled target temperature and its inherited mode:
> 
> Auto setpoints are scheduled temperatures (the default)
> AutoWithEco setpoints are scheduled temperatures, less 3 °C
> If the zone’s target temperature is changed then it will either be a TemporaryOverride or a PermanentOverride, depending. A TemporaryOverride will revert to FollowSchedule after some specified time. A PermanentOverride is a permanent change until some subsequent intervention is made. Zones can be switched between the two override modes without changing the target temperature.
> 
> For some location modes all zones will have a setpoint enforced upon them, regardless of their own mode:
> 
> Away setpoints to 12 °C
> HeatingOff setpoints to a minimum, usually 4 °C
> For Away, the DHW controller will also be turned off.
> 
> Some locations have a hidden mode, AutoWithReset, that will behave as Auto, and will reset all zones to FollowSchedule.
> 
> In the Home Assistant schema, all this is done via a combination of HVAC_MODE and PRESET_MODE (but also see the state attributes system_mode_status and setpoint_status, below).

(Source: https://www.home-assistant.io/integrations/evohome/)

Maybe this could direct you to the root cause?!

**Comment by psy0rz** [comment]
ill screw around in the official app a bit to see if that helps.
