### ISSUE TITLE
Problem Control EvoHome

### ISSUE THREAD

**Issue by proimpel** [dehsgr/node-red-contrib-evohome#2]
Hi,
I'm testing the EvoHome control commands and I found some errors
- sending the command {id: "xxxxxxx"} (where xxxxxxx is my thermostat) the thermostat should return to its program: it does not execute, nothing changes.
- sending the command {id: "xxxxxxx", temperature: 22} (where xxxxxxx is my thermostat) the temperature changes until 01:00 am and not until the next program (21pm)
- sending the command {id: "xxxxxxx", temperatures: 22, endtime: "22:00:00"} (where xxxxxxx is my thermostat) the temperature changes but until 23pm (instead of 22pm)
Could it be the time zone? (I am in Italy)

THANK YOU

**Comment by dehsgr** [comment]
Okay. I pushed a few corrections. Hope this fixes all your needs.
