### ISSUE TITLE
Using multiple Evohome Config nodes returns unexpected Status data

### ISSUE THREAD

**Issue by SylviaDowne** [dehsgr/node-red-contrib-evohome#20]
For a few weeks I have been using your excellent nodes to monitor a new heating system in our local library, plotting actual temperatures/setpoints against the outside temperatures. It is working brilliantly and is proving useful.
However, I recently found out that the nearby Nursery School has a very similar heating system and they have asked me to do the same for them.
So I set up another Evohome Status node plus a new Config node with credentials to access the Nursery system, put an _Inject_ node in front and a _Debug_ node afterwards to test access and identify the zones.
When I ran it I found that it returned exactly the same data as the Library flow.
I updated to the latest version, restarted Node-Red then tried again - and it worked! Unfortunately the Library flow was now returning the Nursery data! I restarted Node-Red once more, the Library now gave me the correct data - but the Nursery flow reverted to the the Library data.
I then set up yet another flow with a new Config node that identified a user with access to both systems. This returned **two** identical copies of the Library data.
The Status node seems to be always using the Config used on first call after Node-Red is started??

**Comment by dehsgr** [comment]
Published new version reflecting your issue. Each flow has its own session store now. So if you put library and nursery in seperate flows, it should work as expected in v1.3.2 and above.

**Comment by SylviaDowne** [comment]
Thank you for the speedy response - it's working fine for me now.
