### ISSUE TITLE
No Data field on nodes

### ISSUE THREAD

**Issue by ChrisHaccour** [dehsgr/node-red-contrib-evohome#23]
Hello dehsgr,

I might be confused, but the "control" and "quickaction" nodes have no field to put values in.
All I have is a "evohome" and a "name" field ....

I'm using node red under Home Assistant, perhaps that makes a difference?
I've also tried restarting my HA, but no difference

Can you help me out?

Regards, Chris.

**Comment by ChrisHaccour** [comment]
![image](https://user-images.githubusercontent.com/46077831/208437595-68756fcf-cab1-42cc-8e0d-6f71c96c9212.png)

**Comment by ChrisHaccour** [comment]
BTW, the "status" node works as described

**Comment by dehsgr** [comment]
You have to inject the data via another node. 😉 

This is nothing special in dependency of node-red or HA.

**Comment by ChrisHaccour** [comment]
Do you mean by something like a "call service" node?
But the controle node has no output, so I can't link another node to it.

**Comment by ChrisHaccour** [comment]
and what is then the advantage of the control node in between?

**Comment by ChrisHaccour** [comment]
or which kind of node do I use to send the json?

**Comment by dehsgr** [comment]
I mean e.g. sth. like an inject node for your first try/tries. The control node is for sending some configuration to evohome; the status node is to retrieve the status.

Sorry, but this is an issue tracker and not a node-red basics support platform. 😉

**Comment by ChrisHaccour** [comment]
yes, I'm sorry that my questions might be pretty basic.
But I'm fairly new to HA/Node Red, I can get around but I'm no expert by any means.
I'll try out a few things and see where I end up, I now got a better idea of how this works (I think ;-))
