### ISSUE TITLE
suggestion for node-red-contrib-evohome

### ISSUE THREAD

**Issue by proimpel** [dehsgr/node-red-contrib-evohome#3]
Hi,
the changes you made work and now it seems there is no problem.
Allow me to give you advice:
It would be nice if the readings, rather than being performed at a fixed rate, were possible "on request" (the evohome status block should also have an entry point)

If you can implement the above I think it's great ....

THANK YOU
REGARDS

**Comment by dehsgr** [comment]
Here you are.
