### ISSUE TITLE
"TypeError: Cannot read property 'locationId' of undefined"

### ISSUE THREAD

**Issue by Dharma1966** [dehsgr/node-red-contrib-evohome#5]
Hi, I'm creating an automation for my heating. I configured the node node-red-contrib-evohome. The problem is that sometimes the system does not connect to the sever giving this error: "TypeError: Cannot read property 'locationId' of undefined". Restarting the Add-ons by Hass.io Node-RED, the error disappears until it reappears after a few calls.Chiaramennte so the automation is not usable ... do you have any advice?

**Comment by dehsgr** [comment]
You might try to increase the polling interval(s).

**Comment by dehsgr** [comment]
See #1

**Comment by Dharma1966** [comment]
Hi, if as a pooling interval you mean the settable one in the status node I tell you that I have tried various values ​​up to switch it off by putting the 0. Despite this every so often the error reappears.

**Comment by dehsgr** [comment]
Issue should be fixed with latest changes. Publishing to NPM.
