### ISSUE TITLE
How to set a zone to a permament temperature ?

### ISSUE THREAD

**Issue by bigwillow99** [dehsgr/node-red-contrib-evohome#7]
Hi.  Thanks for the node-red node for Evo !  
All of the set types seem to be to always resume at the next schedule.  Is there a way to set a zone temperature permamently, I cant see a way to do this  ?
Thanks

**Comment by dehsgr** [comment]
See #6.

Thanks

**Comment by bigwillow99** [comment]
Hi.  Sorry I am new to Github.  Looked at the other post linked, does this mean it will never do it as the API doesnt support it, or you need help from the people that wrote the API ?
Thanks

**Comment by dehsgr** [comment]
No Problem. It means that it is simply not planned at present.

**Comment by bigwillow99** [comment]
Ah right, OK.  Do you know if it is available in the API ?

**Comment by dehsgr** [comment]
Generally it should be possible.

**Comment by bigwillow99** [comment]
Ah OK.  Do you think it is likely to be done at all ?

**Comment by dehsgr** [comment]
Currently it is not planned at all.

**Comment by bigwillow99** [comment]
ok thanks :(
